---
# control
control:
  mask_mode: 'random'
  continue: '0'
# data
data_name: MNIST
# MNIST
model_name: cgan
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
